### ISSUE TITLE
Unable to run the service.

### ISSUE THREAD

**Issue by stackfull** [JanLochi/zigbee2mqtt-snap#1]
I'm not convinced my setup is correct in terms of connecting the serial port, but this looks unrelated.

`2020-12-31T22:35:11Z janlochi-zigbee2mqtt.zigbee2mqtt[732]: node: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory`

Running on a Raspberry Pi 3 B+ with Ubuntu Core (18).

Any hints on how to diagnose would be appreciated, I'm new to snaps.

P.S. thanks for making this.

**Comment by JanLochi** [comment]
Hey, thank you for the feedback.

I agree, this seems unrelated to the serialport config. It's most likely a missing dependency in the snap. I will add it and hope this will fix it. Unfortunately I don't have a device with ARM architecture at hand. Maybe I could test it with an emulated system in the future if demand for this snap rises.

**Comment by JanLochi** [comment]
Version 1.17.0-4 of the snap is currently building, it may fix your issue. Should be done in a few minutes.

**Comment by stackfull** [comment]
That's fixed it! (running `1.17.0-5`).

**Comment by JanLochi** [comment]
Happy to hear! Thank you for letting me know! :-)
