### ISSUE TITLE
How to edit configuration.yaml on Core OS system

### ISSUE THREAD

**Issue by pjgoodall** [JanLochi/zigbee2mqtt-snap#11]
Hi,

I have a Raspberry-pi 2B with Core OS 22. I have this snap installed.
I would like to edit `configuration.yaml`  from the rpi itself.

if I try this:
```
snap get janlochi-zigbee2mqtt -l
error: snap "janlochi-zigbee2mqtt" has no configuration
```

I don't seem to be able to get at the configuration. 

Reccomendations?

**Comment by pjgoodall** [comment]
Looks like you may not have configured your snap to set and get configuration
[snapcraft configuration in snaps](https://snapcraft.io/docs/configuration-in-snaps)

```
~$ snap get -d janlochi-zigbee2mqt
{}
```

**Comment by JanLochi** [comment]
Hi,

You will have to edit the config file directly. See here: https://github.com/JanLochi/zigbee2mqtt-snap#configuration
