### ISSUE TITLE
snap "snapd" has no slot named "usb20-serial"

### ISSUE THREAD

**Issue by Alfiegerner** [JanLochi/zigbee2mqtt-snap#2]
Hi,

New to snap so may be missing something obvious, but when I run:

`sudo snap connect janlochi-zigbee2mqtt:serial-port core:usb20-serial`

I get:

`snap "snapd" has no slot named "usb20-serial"`

Same if I use snaps:usb20-serial.

Any idea what I'm missing? Z2M failing on startup with:

`Error: Error while opening serialport 'Error: Error: Permission denied, cannot open /dev/zzh'`

Which may be down to something unrelated but looks in the right area.

Thanks.

Edit: might have got a bit further, doing

`sudo snap connect janlochi-zigbee2mqtt:serial-port snapd:usbserial`

(Usbserial I got from sudo snap interface serial-port) .

Yep looks like that's sorted that. Onto the next error I'm getting - will close this.

**Comment by JanLochi** [comment]
Hi @Alfiegerner ,

glad that you sorted this out. I will add this information to the README.
