### ISSUE TITLE
EROFS: read-only file system

### ISSUE THREAD

**Issue by Steveo94** [JanLochi/zigbee2mqtt-snap#4]
I am getting these errors when I attempt to start. I am running on a RPI3. I am pretty sure I have the configuration file set up correctly.

Jul 28 21:51:48 Steve janlochi-zigbee2mqtt.zigbee2mqtt[15777]: (node:15812) UnhandledPromiseRejectionWarning: Error: EROFS: read-only file system, mkdir '/snap/janlochi-zigbee2mqtt/35/lib/node_modules/zigbee2mqtt/~'
Jul 28 21:51:48 Steve janlochi-zigbee2mqtt.zigbee2mqtt[15777]:     at Object.mkdirSync (fs.js:1009:3)
Jul 28 21:51:48 Steve janlochi-zigbee2mqtt.zigbee2mqtt[15777]:     at mkdirSyncRecursive (/snap/janlochi-zigbee2mqtt/35/lib/node_modules/zigbee2mqtt/node_modules/mkdir-recursive/index.js:199:16)

Jul 28 21:51:48 Steve janlochi-zigbee2mqtt.zigbee2mqtt[15777]: (Use `node --trace-warnings ...` to show where the warning was created)
Jul 28 21:51:48 Steve janlochi-zigbee2mqtt.zigbee2mqtt[15777]: (node:15812) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Jul 28 21:51:48 Steve janlochi-zigbee2mqtt.zigbee2mqtt[15777]: (node:15812) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by JanLochi** [comment]
Hi, thanks for reporting. Could you please share your configuration file? And which version are you running? `snap list janlochi-zigbee2mqtt` Thx

**Comment by Steveo94** [comment]
Thank you for responding! 

# Optional: Home Assistant integration (MQTT discovery) (default: false)
homeassistant: true

# Optional: allow new devices to join.
# WARNING: Disable this after all devices have been paired! (default: false)
permit_join: true

# Required: MQTT settings
mqtt:
  # Required: MQTT base topic for Zigbee2MQTT MQTT messages
  base_topic: zigbee2mqtt
  # Required: MQTT server URL (use mqtts:// for SSL/TLS connection)
  server: 'mqtt://192.168.80.115:1883'
  # Optional: MQTT server authentication user (default: nothing)
  user: ********
  # Optional: MQTT server authentication password (default: nothing)
  password: *********************


# Required: serial settings
serial:
  # Required: location of the adapter (e.g. CC2531).
  # To autodetect the port, set 'port: null'.
  port: /dev/serial/by-id/ttyUSB0

frontend:
frontend:
  # Optional, default 8080
  port: 8080
  # Optional, default 0.0.0.0
  host: 192.168.1.115
  # Optional, enables authentication, disabled by default
  auth_token: ***************

**Comment by JanLochi** [comment]
I'm not sure if it's related, but your config has some issues.

1. the statement 'frontend:' should only appear once
2. the serial port address seems incorrect, do you really see 'ttyUSB0' if you enter `ls /dev/serial/by-id/` in a console?

**Comment by Steveo94** [comment]
1. You are right. "frontend" does only occur once in my config. That must have happened when I was coping it over to this post. I wasn't able to copy in VIM, so I did it by hand. 
2. When I do `ls /dev/serial/by-id/` I get `usb-Silicon_Labs_HubZ_Smart_Home_Controller_81300F6C-if00-port0` along with these warnings:
```

Aug  2 09:26:57 Steve janlochi-zigbee2mqtt.zigbee2mqtt[21515]: (Use `node --trace-warnings ...` to show where the warning was created)
Aug  2 09:26:57 Steve janlochi-zigbee2mqtt.zigbee2mqtt[21515]: (node:21556) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Aug  2 09:26:57 Steve janlochi-zigbee2mqtt.zigbee2mqtt[21515]: (node:21556) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Aug  2 09:26:57 Steve systemd[1]: snap.janlochi-zigbee2mqtt.zigbee2mqtt.service: Succeeded.
```
My homeassistant is unable to access it, and I can't access the frontend.

**Comment by JanLochi** [comment]
In this case your config should read:

```
serial:
  port: /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_81300F6C-if00-port0
```

And the serial slot of the snap must be connected as described here: https://github.com/JanLochi/zigbee2mqtt-snap/blob/main/README.md

I do not recognize your Zigbee USB adapter, not that I am an expert. Just to be sure, is it a supported device as listed here: https://www.zigbee2mqtt.io/information/supported_adapters.html ?

**Comment by JanLochi** [comment]
Close due to inactivity.
