### ISSUE TITLE
config location

### ISSUE THREAD

**Issue by JohnMcLear** [JanLochi/zigbee2mqtt-snap#5]
README expects it to be at ``/var/snap/zigbee2mqtt/current`` but for me after install it was at ``var/snap/janlochi-zigbee2mqtt/current``

Docs wrong or am I being an idjit? 🖌️ 

Same for ``sudo snap restart janlochi-zigbee2mqtt.zigbee2mqtt ``

**Comment by JanLochi** [comment]
Thanks for noticing. I have planed to release the snap without the prefix, but it never came to it. I will adapt the readme accordingly.
